name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # -------------------
  # Job 1: Build & Push Docker Image
  # -------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/html-demo:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/html-demo:latest

  # -------------------
  # Job 2: Deploy to GitHub Pages
  # -------------------
  deploy:
    runs-on: ubuntu-latest
    needs: docker   # run only after Docker job succeeds
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./   # root directory (index.html is here)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4




















############################ Old Code ############################

# name: Build and Push Docker Image

# on:
#   push:
#     branches: [ main ]

# jobs:
#   docker:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Log in to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build Docker image
#         run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/html-demo:latest .

#       - name: Push Docker image
#         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/html-demo:latest

#       # ---- Add GitHub Pages deployment steps here ----
#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: ./   # change to ./build or ./dist if you generate a build folder

#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4
